/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sjl_jnidata_JniDataTransfer */

#ifndef _Included_com_sjl_jnidata_JniDataTransfer
#define _Included_com_sjl_jnidata_JniDataTransfer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    testPrimitiveType
 * Signature: (BICDLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sjl_jnidata_JniDataTransfer_testPrimitiveType
  (JNIEnv *, jclass, jbyte, jint, jchar, jdouble, jstring);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    getCurrentTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sjl_jnidata_JniDataTransfer_getCurrentTime
  (JNIEnv *, jclass);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    testBytes
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_sjl_jnidata_JniDataTransfer_testBytes
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    testObj
 * Signature: (Lcom/sjl/jnidata/Simple;)V
 */
JNIEXPORT void JNICALL Java_com_sjl_jnidata_JniDataTransfer_testObj
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    testComplexObj
 * Signature: (Lcom/sjl/jnidata/Person;)V
 */
JNIEXPORT void JNICALL Java_com_sjl_jnidata_JniDataTransfer_testComplexObj
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    testGetObj
 * Signature: ()Lcom/sjl/jnidata/Simple;
 */
JNIEXPORT jobject JNICALL Java_com_sjl_jnidata_JniDataTransfer_testGetObj
  (JNIEnv *, jclass);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    testGetComplexObj
 * Signature: ()Lcom/sjl/jnidata/Person;
 */
JNIEXPORT jobject JNICALL Java_com_sjl_jnidata_JniDataTransfer_testGetComplexObj
  (JNIEnv *, jclass);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    setFieldValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sjl_jnidata_JniDataTransfer_setFieldValue
  (JNIEnv *, jobject);

/*
 * Class:     com_sjl_jnidata_JniDataTransfer
 * Method:    setFlag
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_sjl_jnidata_JniDataTransfer_setFlag
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
